### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ghost** [danielriosgarza/MAMBO#10]
```
Traceback (most recent call last):
File "<stdin>", line 3, in <module>
File "bottom_up_ecology.pyx", line 104, in bottom_up_ecology.single_MCMC_run
IndexError: list index out of range
```

Have you run into this before? I am trying to run the following:

```
for i in xrange(100000):
    print(i)
    bte.single_MCMC_run(numpy.random.random_integers(0, len(metabs)), models, initial_environment, metabs, relative_abundance, evolution_of_exchange_reactions , i)
```

**Comment by 990201** [comment]
Hello, have you solved your problem?
